[project]
name = "vizible"
version = "1.0.0a1"
description = "Basic visualization utilities with minimal dependencies."
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"