[project]
name = "vizible"
version = "1.0.0a1"
description = "Basic visualization utilities with minimal dependencies."
requires-python = ">=3.13"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["vizible"]